### ISSUE TITLE
Maven build terminates execution

### ISSUE THREAD

**Issue by ajesh77** [abstratt/textuml#111]
Generating UML files using maven terminates the build once the conversion is complete. Because of this, any other plugins that follow will be ignored and the artifact jar does not created.

The build ends once the UML models are generated from TUML files. org.eclipse.equinox.launcher.Main invoked from the plugin "exec-maven-plugin" terminates the process. Probably a call to System.exit. 

[standalone-pom.zip](https://github.com/abstratt/textuml/files/591067/standalone-pom.zip)

**Comment by abstratt** [comment]
This is due to us running an Eclipse application within the current VM. An Eclipse instance will either call System.exit(...) when the Eclipse application finishes, or stay running indefinitely (if the -noExit) option is given, but either way it will never return control to the caller.

The only way around this I could find was to use the exec goal instead of the java goal for the maven-exec plugin:

```
					<execution>
						<phase>process-resources</phase>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>java</executable>
							<arguments>
								<argument>-Dargs.input=${args.input}</argument>
								<argument>-jar</argument>
								<argument>-jar</argument>
								<argument>
${project.build.directory}/mdd-cli/plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
								</argument>
								<argument>-consoleLog</argument>
							</arguments>
						</configuration>
					</execution>
``` 

One caveat is that now you have to have java in the system path. If that is an issue, you may be able to avoid having to do that by using the 'java.home' system property as a prefix to the executable):

```
		<executable>${java.home}/bin/java</executable>
```

**Comment by abstratt** [comment]
Another approach would be to run the TextUML Compiler as a regular Java application (which is now supported), but that means running the TextUML Compiler with older 3rd-party dependencies (including EMF and UML2), due to lack of up-to-date versions of Eclipse plugins in Maven repositories. 

@ajesh77 I am marking this as closed as I am assuming using the exec goal works for you. Please reopen if that is not the case. There is anything I can change in the codebase itself afaik.

**Comment by ajesh77** [comment]
The suggested change worked. Since we already have JAVA_HOME set up in the system, this should work in all environments.

**Comment by ajesh77** [comment]
Thanks Rafael. The suggested change worked. Since we already have JAVA_HOME
set up in the system, this should work in all environments.
​
​Thanks,
Ajesh A​

**Comment by abstratt** [comment]
Thanks, @ajesh77 . Apparently maven can find any [JDK executable](http://www.mojohaus.org/exec-maven-plugin/examples/example-exec-using-toolchains.html#The_jdk_Toolchain) by default.
